print('\N{GREEK SMALL LETTER PI}r\N{SUPERSCRIPT TWO}')
print('\N{GREEK CAPITAL LETTER THETA}r\N{SUBSCRIPT TWO}')
print('H\N{SUBSCRIPT TWO}O')
print('KMnO\N{SUBSCRIPT FOUR}')
print('H\N{SUBSCRIPT TWO}SO\N{SUBSCRIPT FOUR}')
print('H\N{SUBSCRIPT THREE}PO\N{SUBSCRIPT FOUR}')
print('Acetic acid \t CH\N{SUBSCRIPT THREE}COOH')
print('Sodium phosphate \t Na\N{SUBSCRIPT THREE}PO\N{SUBSCRIPT FOUR}')
print('Ammonium sulfate \t (NH)\N{SUBSCRIPT TWO}SO\N{SUBSCRIPT FOUR}')


